# Generated by Django 3.2.10 on 2021-12-15 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskboardapp', '0002_auto_20211215_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskboard',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskboard',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskboardapp.workproject'),
        ),
        migrations.AlterField(
            model_name='workproject',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='workproject',
            name='project_user',
            field=models.ManyToManyField(related_name='Участники', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workproject',
            name='repository_link',
            field=models.URLField(null=True, verbose_name='ссылка на проект'),
        ),
    ]
