# Generated by Django 3.2.10 on 2021-12-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboardapp', '0003_auto_20211215_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='workproject',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
