# Generated by Django 3.2.10 on 2021-12-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboardapp', '0004_workproject_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workproject',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='taskboard',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
