# Generated by Django 3.2.10 on 2022-01-09 14:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskboardapp', '0005_auto_20211220_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workproject',
            name='project_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
    ]
